apiVersion: skupper.io/v1alpha1
kind: Site
metadata:
  name: east
  namespace: east
  links:
    - secret: west-token-1
---
apiVersion: skupper.io/v1alpha1
kind: Site
metadata:
  name: west
  namespace: west
  tokens:
    - secret: west-token-1
---
apiVersion: v1
kind: Secret
metadata:
  name: west-token-1
  namespace: west
  labels:
    skupper.io/type: token-request
---
apiVersion: skupper.io/v1alpha1
kind: ProvidedService
metadata:
  name: backend
  namespace: east
spec:
  target: deployment/backend
  ports:
    - port: 8080
---
apiVersion: skupper.io/v1alpha1
kind: RequiredService
metadata:
  name: backend
  namespace: west
spec:
  ports:
    - port: 8080
