# west.yaml

apiVersion: skupper.io/v1alpha1
kind: Site
metadata:
  name: west
  namespace: west
---
apiVersion: skupper.io/v1alpha1
kind: RequiredService
metadata:
  name: backend
  namespace: west
spec:
  ports:
    - port: 8080

# east.yaml

apiVersion: skupper.io/v1alpha1
kind: Site
metadata:
  name: east
  namespace: east
---
apiVersion: skupper.io/v1alpha1
kind: ProvidedService
metadata:
  name: backend
  namespace: east
spec:
  target: listener/localhost
  ports:
    - port: 8080

# export KUBECONFIG=~.kube/config-west
# kubectl apply -f west.yaml
# skupper-generate-bundle east.yaml east.tar.gz
# scp east.tar.gz somehost:
# ssh somehost
# tar -xf east.tar.gz
# sh east/install.sh
