global_arguments:
  - name: --help
    description: |
      Display help and exit.
  - name: --context
    type: string
    description: |
      Select the kubeconfig context.
  - name: --namespace
    type: string
    description: |
      Select the Kubernetes namespace.
  - name: --platform
    type: string
    description: |
      Select the Skupper platform.
groups:
  - name: Site configuration
    commands:
      - name: site
        description: |
          Display help for site commands and exit.
      - name: site create
        concept: site
        resource: Site
        description: |
          Create a site.

          @resource_description@
        usage: skupper site create <name> [options]
        examples: |
          # Create a site
          skupper site create west

          # Create a site that can accept links from remote sites
          skupper site create west --enable-link-access
        output: |
          Waiting for status...
          Site "<name>" is ready
        arguments:
          - name: name
            type: string
            required: true
            description: |
              A name of your choice for the Skupper site.  This name is
              displayed in the console and CLI output.
          - name: --enable-link-access
            type: boolean
            description: |
              Allow access for incoming links from remote sites.
          - property: linkAccess
            name: --link-access-type
            default: default
          - property: serviceAccount
        errors:
          - message: A site resource already exists
            description: |
              There is already a site resource defined for the namespace.
      - name: site update
        resource: Site
        description: |
          Change site settings.

          The name argument is optional for update.
        usage: skupper site update [name] [options]
        examples: |
          # Update the site to accept links
          skupper site update --enable-link-access

          # Update multiple settings
          skupper site update --enable-link-access --service-account app1:alice
        output: |
          Waiting for update to complete...
          Site "<name>" is updated
        arguments:
          - name: name
            type: string
            description: |
              This is optional!  We use the site associated with the
              current namespace if the name is not given.

              The name of the site resource.
          - name: --enable-link-access
            type: boolean
            description: |
              Allow access for incoming links from remote sites.
          - property: linkAccess
            name: --link-access-type
            default: default
          - property: serviceAccount
        errors:
          - message: No site resource exists
            description: |
              There is no existing Skupper site resource to update.
      - name: site delete
        description: |
          Delete a site.
        links:
          - name: Skupper sites
            url: "/concepts.html#site"
        usage: skupper site delete [name]
        output: |
          Waiting for deletion to complete...
          Site "<name>" is deleted
        arguments:
          - name: name
            type: string
            description: |
              The name of the site resource.
        errors:
          - message: No site resource exists
            description: |
              There is no existing Skupper site resource to delete.
      - name: site status
        description: |
          Show the current status of a site.
        usage: skupper site status
        output: |
          NAME   STATUS   SITES-IN-NETWORK   SERVICES-IN-NETWORK
          west   Ready    1                  0
        notes: |
          What is services-in-network?  Is that the total number of
          unique routing keys defined by connectors?  Or listeners?
          Or listeners plus connectors (not the orphans), grouped by
          routing key?
  - name: Site linking
    commands:
      - name: token
        description: |
          Display help for token commands and exit.  Currently there
          is only one token command.
      - name: token create
        resource: Grant
        description: |
          Create a token.
        usage: skupper token create <file> [options]
        output: |
          Token file <file> created
          The token expires after 1 use or after 15 minutes
        arguments:
          - name: file
            type: string
            description: |
              The name of the token file.
          - property: validFor
            name: --expiry
            type: string
            format: duration
            default: 15m
          - property: claims
            name: --uses
            default: 1
      - name: token redeem
        resource: Claim
        description: |
          Redeem a token for a link.

          @resource_description@
        usage: skupper token redeem <file> [options]
        output: |
          Waiting for status...
          Link "<name>" is active
          You can now safely delete <file>
        arguments:
          - name: file
            description: |
              The name of the token file.
      - name: link
        description: |
          Display help for link commands and exit.
      - name: link delete
        usage: skupper link delete <name>
      - name: link status
        output: |
          NAME    STATUS   COST
          west    Active   1
          south   Error    10

          Links from remote sites:

          None
  - name: Service exposure
    commands:
      - name: connector
        description: |
          Display help for connector commands and exit.
      - name: connector create
        resource: Connector
        description: |
          Create a connector.

          @resource_description@
        usage: skupper connector create <name> [options]
        examples: |
          # Create a connector for a database
          skupper connector create database --workload deployment/postgresql --port 5432
        output: |
          Waiting for status...
          Connector "<name>" is ready
        arguments:
          - name: name
            type: string
            required: true
            description: |
              The name of the connector resource.
          - property: routingKey
            default: _value of name_
          - name: --workload
            type: string
          - property: port
          - property: selector
          - property: host
          - property: tlsCredentials
          - property: type
          - property: includeNotReady
      - name: connector delete
        description: |
          Delete a connector.
        usage: skupper connector delete <name>
        output: |
          Waiting for deletion to complete...
          Connector "<name>" is deleted
        arguments:
          - name: name
            type: string
            description: |
              The name of the connector resource.
      - name: connector status
        description: |
          Show the status of connectors in the current site.
        usage: skupper connector status
        output: |
          NAME       ROUTING-KEY   SELECTOR         HOST   PORT   MATCHING-LISTENERS
          backend    backend       app=backend      -      8080   1
          database   database      app=postgresql   -      5342   1
      - name: listener
        description: |
          Display help for listener commands and exit.
      - name: listener create
        resource: Listener
        description: |
          Create a listener.

          @resource_description@
        usage: skupper listener create <name> [options]
        examples: |
          # Create a listener for a database
          skupper listener create database --host database --port 5432
        output: |
          Waiting for status...
          Listener "<name>" is ready
        arguments:
          - name: name
            type: string
            description: |
              The name of the listener resource.
          - property: routingKey
            default: _value of name_
          - property: host
          - property: port
          - property: tlsCredentials
          - property: type
      - name: listener delete
        description: |
          Delete a listener.
        usage: skupper listener delete <name>
        output: |
          Waiting for deletion to complete...
          Listener "<name>" is deleted
        arguments:
          - name: name
            type: string
            description: |
              The name of the listener resource.
      - name: listener status
        description: |
          Show the status of listeners in the current site.
        usage: skupper listener status
        output: |
          NAME       ROUTING-KEY   HOST       PORT   MATCHING-CONNECTORS
          backend    backend       backend    8080   1
          database   database      database   5432   1
  # - name: Platform operations
  #   commands:
  #     - name: platform
  #       description: |
  #         Display help for platform commands and exit.
  #     - name: platform install
  #     - name: platform uninstall
  #     - name: platform switch
  - name: Debug operations
    commands:
      - name: debug
        description: |
          Display help for debug commands and exit.
      - name: debug dump
        description: |
          Generate a debug dump file.
        usage: skupper debug dump [file]
        output: |
          Debug dump file generated at <file>
  - name: Other operations
    commands:
      # - name: network status
      - name: version
