options:
  mutable_site_configuration:
    - name: --enable-link-access
      default: false
      description: |
        Enable external access for links from remote sites.
    - name: --link-access-type
      variable: string
      default: _platform dependent_
      description: |
        Select the means of opening external access.

        The default is `route` on OpenShift and `loadbalancer`
        otherwise.
    - name: --service-account
      variable: string
      default: _I don't know_
global_options:
  - name: --help
    description: |
      Display help and exit.
  - name: --context
    variable: string
    description: |
      Select the kubeconfig context.
  - name: --namespace
    variable: string
    description: |
      Select the Kubernetes namespace.
  - name: --platform
    variable: string
    description: |
      Select the Skupper platform.
groups:
  - title: Site configuration
    commands:
      - title: skupper site
        description: |
          Display help for site commands and exit.
      - title: skupper site create
        description: |
          Create a site.
        usage: skupper site create NAME [options]
        examples: |
          # Create a site
          skupper site create west

          # Create a site that can accept links from remote sites
          skupper site create west --enable-link-access
        output: |
          Waiting for status...
          Site "<name>" is ready
        options:
          - include: mutable_site_configuration
        errors:
          - message: Site resource already exists
            description: |
              There is already a site resource defined for the namespace.
      - title: skupper site update
        description: |
          Change site settings.
        usage: skupper site update NAME [options]
        examples: |
          # Update the site to accept links
          skupper site update west --enable-link-access

          # Update multiple settings
          skupper site update west --enable-link-access --link-access-type loadbalancer
        output: |
          Waiting for update to complete...
          Site "<name>" is updated
        options:
          - include: mutable_site_configuration
        errors:
          - message: No site resource exists
            description: |
              There is no existing Skupper site resource to update.
      - title: skupper site delete
        description: |
          Delete a site.
        usage: skupper site delete NAME
        output: |
          Waiting for deletion to complete...
          Site "<name>" is deleted
        errors:
          - message: No site resource exists
            description: |
              There is no existing Skupper site resource to delete.
      - title: skupper site status
        description: |
          Show the current status of a site.
        usage: skupper site status
        output: |
          NAME   STATUS   SITES-IN-NETWORK   SERVICES-IN-NETWORK
          west   Ready    1                  0
        notes: |
          What is services-in-network?  Is that the total number of
          unique routing keys defined by connectors?  Or listeners?
          Or listeners plus connectors (not the orphans), grouped by
          routing key?
  - title: Site linking
    commands:
      - title: skupper token
        description: |
          Display help for token commands and exit.  Currently there
          is only one token command.
      - title: skupper token create
        description: |
          Create a token.
        usage: skupper token create FILE [options]
        output: |
          Token file created at <file>
          The token expires after 1 use or after 15 minutes
        options:
          - name: --expiry
            variable: duration
            default: 15m
          - name: --uses
            variable: integer
            default: 1
      - title: skupper link
        description: |
          Display help for link commands and exit.
      - title: skupper link create
        description: |
          Create a link.
        usage: skupper link create FILE [options]
        output: |
          Waiting for status...
          Link "<name>" is active
          You can now safely delete <file>
        options:
          - name: --cost
            variable: integer
            default: 1
      - title: skupper link delete
        usage: skupper link delete NAME
      - title: skupper link status
        output: |
          NAME   STATUS   COST
          west   Active   1

          Links from remote sites:

          None
  - title: Service exposure
    commands:
      - title: skupper connector
        description: |
          Display help for connector commands and exit.
      - title: skupper connector create
        description: |
          Create a connector.
        usage: skupper connector create NAME [options]
        examples: |
          # Create a connector for a database
          skupper connector create database --workload deployment/database --port 5432
        output: |
          Waiting for status...
          Connector "<name>" is ready
        options:
          - name: --routing-key
            variable: string
            default: _value of NAME_
          - name: --port
            variable: integer
          - name: --workload
            variable: string
          - name: --selector
            variable: string
          - name: --host
            variable: string
      - title: skupper connector delete
        description: |
          Delete a connector.
        usage: skupper connector delete NAME
        output: |
          Waiting for deletion to complete...
          Connector "<name>" is deleted
      - title: skupper connector status
        description: |
          Show the status of connectors in the current site.
        usage: skupper connector status
        output: |
          NAME      ROUTING-KEY   SELECTOR      PORT   MATCHING-LISTENERS
          backend   backend       app=backend   8080   1
      - title: skupper listener
        description: |
          Display help for listener commands and exit.
      - title: skupper listener create
        description: |
          Create a listener.
        usage: skupper listener create NAME [options]
        examples: |
          # Create a listener for a database
          skupper listener create database --host database --port 5432
        output: |
          Waiting for status...
          Listener "<name>" is ready
        options:
          - name: --routing-key
            variable: string
            default: _value of NAME_
          - name: --host
            variable: string
          - name: --port
            variable: integer
      - title: skupper listener delete
        description: |
          Delete a listener.
        usage: skupper listener delete NAME
        output: |
          Waiting for deletion to complete...
          Listener "<name>" is deleted
      - title: skupper listener status
        description: |
          Show the status of listeners in the current site.
        usage: skupper listener status
        output: |
          NAME      ROUTING-KEY   HOST      PORT   MATCHING-CONNECTORS
          backend   backend       backend   8080   1
  # - title: Platform operations
  #   commands:
  #     - title: skupper platform
  #       description: |
  #         Display help for platform commands and exit.
  #     - title: skupper platform install
  #     - title: skupper platform uninstall
  #     - title: skupper platform switch
  - title: Debug operations
    commands:
      - title: skupper debug
        description: |
          Display help for debug commands and exit.
      - title: skupper debug dump
        description: |
          Generate a debug dump file.
        usage: skupper debug dump [FILE]
        output: |
          Debug dump file generated at <file>
  - title: Other operations
    commands:
      # - title: skupper network status
      - title: skupper version
