standard_options:
  context:
    name: Context options
    options:
      - name: namespace
        type: string
        description: |
          Select the current namespace.
      - name: context
        type: string
        description: |
          Select the current kubeconfig context.
        platforms: [Kubernetes]
      - name: platform
        type: string
        choices:
          - name: kubernetes
            description: Kubernetes
          - name: docker
            description: Docker or Podman
        description: |
          Set the Skupper platform.
  output:
    name: Output options
    options:
      - name: output
        type: string
        description: |
          Print resources to the console instead of submitting
          them to the Skupper controller.
        choices:
          - name: json
            description: Produce JSON output
          - name: yaml
            description: Produce YAML output
  global:
    name: Global options
    options:
      - name: help
        type: ""
        description: |
          Display help and exit.
groups:
  - name: Sites
    commands:
      - name: site
        description: |
          Display help for site commands and exit.

          @resource_description@
      - name: site create
        description: |
          Create a site.
        usage: skupper site create <name> [options]
        examples: |
          # Create a site
          skupper site create west

          # Create a site that can accept links from remote sites
          skupper site create west --enable-link-access
        output: |
          Waiting for status...
          Site "<name>" is ready.
        inherit_standard_options: [output, context, global]
        options:
          - name: name
            type: string
            required: true
            description: |
              A name of your choice for the Skupper site.  This name is
              displayed in the console and CLI output.
          - name: enable-link-access
            type: boolean
            description: |
              Allow access for incoming links from remote sites.
          - name: link-access-type
            property: linkAccess
            default: default
            choices:
              - name: default
                description: |
                  Use the default link access.  On OpenShift, the
                  default is `route`.  For other Kubernetes flavors,
                  the default is `loadbalancer`.
              - name: route
                description: Use an OpenShift route.  _OpenShift only._
              - name: loadbalancer
                description: Use a Kubernetes load balancer.  _Kubernetes only._
          - name: service-account
            property: serviceAccount
        errors:
          - message: A site resource already exists
            description: |
              There is already a site resource defined for the namespace.
      - name: site update
        description: |
          Change site settings.
        usage: skupper site update [name] [options]
        examples: |
          # Update the site to accept links
          skupper site update --enable-link-access

          # Update multiple settings
          skupper site update --enable-link-access --service-account app1:alice
        output: |
          Waiting for update to complete...
          Site "<name>" is updated.
        inherit_command_options: site create
        inherit_standard_options: [output, context, global]
        options:
          - name: name
            type: string
            required: false
            positional: true
            description: |
              The name of the site resource.

              If not specified, the name is that of the site
              associated with the current namespace.
        errors:
          - message: No site resource exists
            description: |
              There is no existing Skupper site resource to update.
      - name: site delete
        description: |
          Delete a site.
        usage: skupper site delete [name]
        output: |
          Waiting for deletion to complete...
          Site "<name>" is deleted.
        inherit_standard_options: [context, global]
        options:
          - name: name
            type: string
            positional: true
            description: |
              The name of the site resource.

              If not specified, the name is that of the site
              associated with the current namespace.
        errors:
          - message: No site resource exists
            description: |
              There is no existing Skupper site resource to delete.
      - name: site status
        description: |
          Display the current status of a site.
        usage: skupper site status
        output: |
          NAME   STATUS   SITES-IN-NETWORK   SERVICES-IN-NETWORK
          west   Ready    1                  0
        inherit_standard_options: [context, global]
        notes: |
          What is services-in-network?  Is that the total number of
          unique routing keys defined by connectors?  Or listeners?
          Or listeners plus connectors (not the orphans), grouped by
          routing key?
  - name: Site linking
    commands:
      - name: token
        resource: Claim
        description: |
          Display help for token commands and exit.
        inherit_standard_options: [global]
      - name: token issue
        resource: Grant
        links:
          - name: token redeem command
            url: /commands/token-redeem.html
        description: |
          Issue a token redeemable for a link to the current site.

          Issue a token that can be redeemed at a remote site for a
          link to the current site.

          This command first creates a grant in order to issue the
          token.
        usage: skupper token issue <file> [options]
        output: |
          Waiting for status...
          Grant "<name>" is ready.
          Token file <file> created.

          Transfer this file to a remote site. At the remote site,
          create a link to this site using the 'skupper token
          redeem' command:

             $ skupper token redeem <file>

          The token expires after 1 use or after 15 minutes.
        examples: |
          # Issue an access token
          skupper token issue ~/token.yaml

          # Issue an access token with non-default limits
          skupper token issue ~/token.yaml --expiration-window 24h --redemptions-allowed 3
        inherit_standard_options: [context, global]
        options:
          - name: file
            type: string
            required: true
            description: |
              The name of the token file.
          - name: expiration-window
            property: validFor
          - name: redemptions-allowed
            property: claims
        errors:
          - message: Link access is not enabled
            description: |
              Link access at this site is not currently enabled.  You
              can use "skupper site update --enable-link-access" to
              enable it.
      - name: token redeem
        links:
          - name: token issue command
            url: /commands/token-issue.html
        description: |
          Redeem a token in order to obtain a link to a remote site.
        usage: skupper token redeem <file> [options]
        output: |
          Waiting for status...
          Link "<name>" is active.
          You can now safely delete <file>.
        inherit_standard_options: [context, global]
        options:
          - name: file
            type: string
            required: true
            description: |
              The name of the token file.
      - name: link
        description: |
          Display help for link commands and exit.

          @resource_description@
        inherit_standard_options: [global]
      - name: link create
        description: |
          Create a link.
        usage: skupper link create <name> <tls-secret>
        output: |
          Waiting for status...
          Link "<name>" is ready.
        inherit_standard_options: [output, context, global]
        options:
          - name: name
            type: string
            required: true
            description: |
              The name of the link.
          - name: tls-secret
            property: tlsCredentials
            required: true
            positional: true
      - name: link update
        description: |
          Change link settings.
        usage: skupper link update <name> [options]
        output: |
          Waiting for update to complete...
          Link "<name>" is updated.
        inherit_command_options: link create
        inherit_standard_options: [output, context, global]
        options:
          - name: tls-secret
            property: tlsCredentials
      - name: link delete
        description: |
          Delete a link.
        usage: skupper link delete <name>
        output: |
          Waiting for deletion to complete...
          Link "<name>" is deleted.
        inherit_standard_options: [context, global]
        options:
          - name: name
            type: string
            required: true
            description: |
              The name of the link.
      - name: link status
        description: |
          Display the status of links in the current site.
        output: |
          NAME    STATUS   COST
          west    Active   1
          south   Error    10

          Links from remote sites:

          [None]
        inherit_standard_options: [output, context, global]
  - name: Service exposure
    commands:
      - name: connector
        description: |
          Display help for connector commands and exit.
        inherit_standard_options: [global]
      - name: connector create
        links:
          - name: listener create command
            url: /commands/listener-create.html
        description: |
          Create a connector.
        usage: skupper connector create <name> <port> [options]
        examples: |
          # Create a connector for a database
          skupper connector create database 5432

          # Set the routing key and workload explicitly
          skupper connector create backend 8080 --routing-key be1 --workload deployment/backend

          # Produce YAML output
          skupper connector create backend 8080 --output yaml
        output: |
          Waiting for status...
          Connector "<name>" is ready.
        inherit_standard_options: [output, context, global]
        options:
          - name: name
            type: string
            required: true
            description: |
              The name of the connector resource.
          - name: port
            property: port
            positional: true
          - name: routing-key
            property: routingKey
            default: _Value of name_
          - name: selector
            property: selector
            default: app=<value-of-name>
          - name: workload
            type: string
            format: resource name
            description: |
              A Kubernetes resource name that identifies a workload.
              It resolves to an equivalent pod selector.

              This is an alternative to setting the `--selector` or
              `--host` options.
            platforms: [Kubernetes]
            links:
              - name: Kubernetes workloads
                url: https://kubernetes.io/docs/concepts/workloads/
          - name: host
            property: host
            description: |
              The hostname or IP address of the server.

              This is an alternative to setting the `--selector` or
              `--workload` options.
          - name: tls-secret
            property: tlsCredentials
          - name: type
            property: type
          - name: include-not-ready
            property: includeNotReady
      - name: connector update
        links:
          - name: listener update command
            url: /commands/listener-update.html
        description: |
          Update a connector.
        usage: skupper connector update <name> [options]
        examples: |
          # Change the workload and port
          skupper connector update database --workload deployment/mysql --port 3306

          # Change the routing key
          skupper connector update backend --routing-key be2

          # Produce YAML output
          skupper connector update frontend --port 9090 --output yaml
        output: |
          Waiting for update to complete...
          Connector "<name>" is updated.
        inherit_command_options: connector create
        inherit_standard_options: [output, context, global]
        options:
          - name: port
            property: port
            required: false
      - name: connector delete
        links:
          - name: listener delete command
            url: /commands/listener-delete.html
        description: |
          Delete a connector.
        usage: skupper connector delete <name>
        output: |
          Waiting for deletion to complete...
          Connector "<name>" is deleted.
        inherit_standard_options: [context, global]
        options:
          - name: name
            type: string
            required: true
            description: |
              The name of the connector resource.
      - name: connector status
        description: |
          Display the status of connectors in the current site.
        usage: skupper connector status
        output: |
          NAME       ROUTING-KEY   SELECTOR         HOST   PORT   MATCHING-LISTENERS
          backend    backend       app=backend      -      8080   1
          database   database      app=postgresql   -      5432   1
      - name: listener
        description: |
          Display help for listener commands and exit.
      - name: listener create
        links:
          - name: connector create command
            url: /commands/connector-create.html
        description: |
          Create a listener.
        usage: skupper listener create <name> <port> [options]
        examples: |
          # Create a listener for a database
          skupper listener create database 5432

          # Set the routing key and host explicitly
          skupper listener create backend 8080 --routing-key be1 --host apiserver

          # Produce YAML output
          skupper listener create frontend 8080 --output yaml
        output: |
          Waiting for status...
          Listener "<name>" is ready.
        inherit_standard_options: [output, context, global]
        options:
          - name: name
            type: string
            required: true
            description: |
              The name of the listener resource.
          - name: port
            property: port
            positional: true
          - name: routing-key
            property: routingKey
            default: _Value of name_
          - name: host
            property: host
            default: _Value of name_
          - name: tls-secret
            property: tlsCredentials
          - name: type
            property: type
      - name: listener update
        links:
          - name: connector update command
            url: /commands/connector-update.html
        description: |
          Update a listener.
        usage: skupper listener update <name> [options]
        examples: |
          # Change the host and port
          skupper listener update database --host mysql --port 3306

          # Change the routing key
          skupper listener update backend --routing-key be2

          # Produce YAML output
          skupper listener update frontend --port 9090 --output yaml
        output: |
          Waiting for update to complete...
          Listener "<name>" is updated.
        inherit_command_options: listener create
        inherit_standard_options: [output, context, global]
        options:
          - name: port
            property: port
            required: false
      - name: listener delete
        links:
          - name: connector delete command
            url: /commands/connector-delete.html
        description: |
          Delete a listener.
        usage: skupper listener delete <name>
        output: |
          Waiting for deletion to complete...
          Listener "<name>" is deleted.
        inherit_standard_options: [context, global]
        options:
          - name: name
            type: string
            required: true
            description: |
              The name of the listener resource.
      - name: listener status
        description: |
          Display the status of listeners in the current site.
        usage: skupper listener status
        output: |
          NAME       ROUTING-KEY   HOST       PORT   MATCHING-CONNECTORS
          backend    backend       backend    8080   1
          database   database      database   5432   1
        inherit_standard_options: [output, context, global]
  - name: Debug operations
    commands:
      - name: debug
        description: |
          Display help for debug commands and exit.
      - name: debug dump
        description: |
          Generate a debug dump file.
        usage: skupper debug dump [file]
        output: |
          Debug dump file generated at <file>.
  - name: Other operations
    commands:
      # - name: network status
      - name: version
        description: |
          Display versions of Skupper components
