global_arguments:
  - name: --help
    description: |
      Display help and exit.
  - name: --context
    type: string
    description: |
      Select the kubeconfig context.
  - name: --namespace
    type: string
    description: |
      Select the Kubernetes namespace.
  - name: --platform
    type: string
    description: |
      Select the Skupper platform.
groups:
  - name: Site configuration
    commands:
      - name: site
        description: |
          Display help for site commands and exit.
      - name: site create
        concept: site
        resource: Site
        description: |
          Create a site.

          @resource_description@
        usage: skupper site create <name> [options]
        examples: |
          # Create a site
          skupper site create west

          # Create a site that can accept links from remote sites
          skupper site create west --enable-link-access
        output: |
          Waiting for status...
          Site "<name>" is ready
        arguments:
          - name: name
            type: string
            required: true
            description: |
              A name of your choice for the Skupper site.  This name is
              displayed in the console and CLI output.
          - name: --enable-link-access
            type: boolean
            description: |
              Allow access for incoming links from remote sites.
          - name: --link-access-type
            property: linkAccess
            default: default
          - name: --service-account
            property: serviceAccount
        errors:
          - message: A site resource already exists
            description: |
              There is already a site resource defined for the namespace.
      - name: site update
        resource: Site
        description: |
          Change site settings.

          The name argument is optional for update.
        usage: skupper site update [name] [options]
        examples: |
          # Update the site to accept links
          skupper site update --enable-link-access

          # Update multiple settings
          skupper site update --enable-link-access --service-account app1:alice
        output: |
          Waiting for update to complete...
          Site "<name>" is updated
        arguments:
          - name: name
            type: string
            description: |
              This is optional!  We use the site associated with the
              current namespace if the name is not given.

              The name of the site resource.
          - name: --enable-link-access
            type: boolean
            description: |
              Allow access for incoming links from remote sites.
          - name: --link-access-type
            property: linkAccess
            default: default
          - name: --service-account
            property: serviceAccount
        errors:
          - message: No site resource exists
            description: |
              There is no existing Skupper site resource to update.
      - name: site delete
        description: |
          Delete a site.
        links:
          - name: Skupper sites
            url: "/concepts.html#site"
        usage: skupper site delete [name]
        output: |
          Waiting for deletion to complete...
          Site "<name>" is deleted
        arguments:
          - name: name
            type: string
            description: |
              The name of the site resource.
        errors:
          - message: No site resource exists
            description: |
              There is no existing Skupper site resource to delete.
      - name: site status
        description: |
          Show the current status of a site.
        usage: skupper site status
        output: |
          NAME   STATUS   SITES-IN-NETWORK   SERVICES-IN-NETWORK
          west   Ready    1                  0
        notes: |
          What is services-in-network?  Is that the total number of
          unique routing keys defined by connectors?  Or listeners?
          Or listeners plus connectors (not the orphans), grouped by
          routing key?
  - name: Site linking
    commands:
      - name: link
        description: |
          Display help for link commands and exit.
      - name: link delete
        usage: skupper link delete <name>
      - name: link status
        output: |
          NAME    STATUS   COST
          west    Active   1
          south   Error    10

          Links from remote sites:

          None
      - name: grant
        resource: Grant
      - name: grant delete
        resource: Grant
      - name: grant status
        resource: Grant
      - name: token
        description: |
          Display help for token commands and exit.
      - name: token issue
        concept: grant
        resource: Grant
        command: token redeem
        description: |
          Create a grant and then use it to create a token file that
          can be redeemed for a link to the local site.
        usage: skupper token issue <file> [options]
        output: |
          Token file <file> created.

          Transfer this file to a remote site. At the remote site,
          create a link to this site using the 'skupper token redeem'
          command:

             $ skupper token redeem <file>

          The token expires after 1 use or after 15 minutes.
        arguments:
          - name: file
            type: string
            required: true
            description: |
              The name of the token file.
          - name: --expiration-period
            property: validFor
          - name: --redemptions-allowed
            property: claims
      - name: token redeem
        concept: claim
        resource: Claim
        command: token issue
        description: |
          Redeem a token for a link to a remote site.
        usage: skupper token redeem <file> [options]
        output: |
          Waiting for status...
          Link "<name>" is active.
          You can now safely delete <file>.
        arguments:
          - name: file
            type: string
            required: true
            description: |
              The name of the token file.
  - name: Service exposure
    commands:
      - name: connector
        description: |
          Display help for connector commands and exit.
      - name: connector create
        concept: connector
        resource: Connector
        command: listener create
        description: |
          Create a connector.

          @resource_description@

          When creating a connector, you must supply a target workload
          using the `--workload`, `--selector`, or `--host` options.
        usage: skupper connector create <name> <port> [options]
        examples: |
          # Create a connector for a database
          skupper connector create database 5432 --workload deployment/postgresql

          # Set the routing key explicitly
          skupper connector create backend 8080 --workload deployment/backend --routing-key be1

          # Produce YAML output
          skupper connector create frontend 8080 --workload deployment/frontend --output yaml
        output: |
          Waiting for status...
          Connector "<name>" is ready
        arguments:
          - name: name
            type: string
            required: true
            description: |
              The name of the connector resource.

              The name also serves as the default routing key if the
              `--routing-key` option is not set.
          - name: port
            property: port
            positional: true
          - name: --routing-key
            property: routingKey
            default: _Value of name_
          - name: --selector
            property: selector
            description: |
              A Kubernetes label selector for targeting server pods.

              This is an alternative to setting the `--workload` or
              `--host` options.
          - name: --workload
            type: string
            format: "<code>&lt;resource-kind&gt;/&lt;resource-name&gt;</code>"
            description: |
              A Kubernetes resource name that identifies a workload.
              It resolves to an equivalent pod selector.

              This is an alternative to setting the `--selector` or
              `--host` options.
            links:
              - name: Kubernetes workloads
                url: https://kubernetes.io/docs/concepts/workloads/
          - name: --host
            property: host
            description: |
              The hostname or IP address of the server.

              This is an alternative to setting the `--selector` or
              `--workload` options.
          - name: --tls-secret
            property: tlsCredentials
          - name: --type
            property: type
          - name: --include-not-ready
            property: includeNotReady
          - name: --output
            type: string
            description: |
              Print resources to the console instead of submitting
              them to the Skupper controller.
            choices:
              - name: json
                description: Produce JSON output
              - name: yaml
                description: Produce YAML output
      - name: connector delete
        description: |
          Delete a connector.
        usage: skupper connector delete <name>
        output: |
          Waiting for deletion to complete...
          Connector "<name>" is deleted
        arguments:
          - name: name
            type: string
            description: |
              The name of the connector resource.
      - name: connector status
        description: |
          Show the status of connectors in the current site.
        usage: skupper connector status
        output: |
          NAME       ROUTING-KEY   SELECTOR         HOST   PORT   MATCHING-LISTENERS
          backend    backend       app=backend      -      8080   1
          database   database      app=postgresql   -      5432   1
      - name: listener
        description: |
          Display help for listener commands and exit.
      - name: listener create
        concept: listener
        resource: Listener
        command: connector create
        description: |
          Create a listener.

          @resource_description@
        usage: skupper listener create <name> <port> [options]
        examples: |
          # Create a listener for a database
          skupper listener create database 5432

          # Set the routing key and host explicitly
          skupper listener create backend 8080 --routing-key be1 --host apiserver

          # Produce YAML output
          skupper listener create frontend 8080 --output yaml
        output: |
          Waiting for status...
          Listener "<name>" is ready
        arguments:
          - name: name
            type: string
            required: true
            description: |
              The name of the listener resource.

              The name also serves as the default routing key and host
              if the `--routing-key` and `--host` options are not set.
          - name: port
            property: port
            positional: true
          - name: --routing-key
            property: routingKey
            default: _Value of name_
          - name: --host
            property: host
            default: _Value of name_
          - name: --tls-secret
            property: tlsCredentials
          - name: --type
            property: type
      - name: listener delete
        description: |
          Delete a listener.
        usage: skupper listener delete <name>
        output: |
          Waiting for deletion to complete...
          Listener "<name>" is deleted
        arguments:
          - name: name
            type: string
            description: |
              The name of the listener resource.
      - name: listener status
        description: |
          Show the status of listeners in the current site.
        usage: skupper listener status
        output: |
          NAME       ROUTING-KEY   HOST       PORT   MATCHING-CONNECTORS
          backend    backend       backend    8080   1
          database   database      database   5432   1
  # - name: Platform operations
  #   commands:
  #     - name: platform
  #       description: |
  #         Display help for platform commands and exit.
  #     - name: platform install
  #     - name: platform uninstall
  #     - name: platform switch
  - name: Debug operations
    commands:
      - name: debug
        description: |
          Display help for debug commands and exit.
      - name: debug dump
        description: |
          Generate a debug dump file.
        usage: skupper debug dump [file]
        output: |
          Debug dump file generated at <file>
  - name: Other operations
    commands:
      # - name: network status
      - name: version
