global_arguments:
  - name: --help
    description: |
      Display help and exit.
  - name: --context
    variable: string
    description: |
      Select the kubeconfig context.
  - name: --namespace
    variable: string
    description: |
      Select the Kubernetes namespace.
  - name: --platform
    variable: string
    description: |
      Select the Skupper platform.
groups:
  - title: Site configuration
    commands:
      - title: skupper site
        description: |
          Display help for site commands and exit.
      - resource: Site
        title: skupper site create
        description: |
          Create a site.

          @resource_description@
        usage: skupper site create <name> [options]
        examples: |
          # Create a site
          skupper site create west

          # Create a site that can accept links from remote sites
          skupper site create west --enable-link-access
        output: |
          Waiting for status...
          Site "<name>" is ready
        arguments:
          - name: name
            variable: string
            description: |
              A name of your choice for the Skupper site.  This name is
              displayed in the console and CLI output.
          - property: enableLinkAccess
          - property: linkAccessType
          - property: linkAccessHost
          - property: serviceAccount
        errors:
          - message: Site resource already exists
            description: |
              There is already a site resource defined for the namespace.
      - resource: Site
        title: skupper site update
        description: |
          Change site settings.
        usage: skupper site update <name> [options]
        examples: |
          # Update the site to accept links
          skupper site update west --enable-link-access

          # Update multiple settings
          skupper site update west --enable-link-access --link-access-type loadbalancer
        output: |
          Waiting for update to complete...
          Site "<name>" is updated
        arguments:
          - name: name
            variable: string
            description: |
              The name of the site resource.
          - property: enableLinkAccess
          - property: linkAccessType
          - property: linkAccessHost
          - property: serviceAccount
        errors:
          - message: No site resource exists
            description: |
              There is no existing Skupper site resource to update.
      - title: skupper site delete
        description: |
          Delete a site.
        usage: skupper site delete <name>
        output: |
          Waiting for deletion to complete...
          Site "<name>" is deleted
        arguments:
          - name: name
            variable: string
            description: |
              The name of the site resource.
        errors:
          - message: No site resource exists
            description: |
              There is no existing Skupper site resource to delete.
      - title: skupper site status
        description: |
          Show the current status of a site.
        usage: skupper site status
        output: |
          NAME   STATUS   SITES-IN-NETWORK   SERVICES-IN-NETWORK
          west   Ready    1                  0
        notes: |
          What is services-in-network?  Is that the total number of
          unique routing keys defined by connectors?  Or listeners?
          Or listeners plus connectors (not the orphans), grouped by
          routing key?
  - title: Site linking
    commands:
      - title: skupper token
        description: |
          Display help for token commands and exit.  Currently there
          is only one token command.
      - resource: Grant
        title: skupper token create
        description: |
          Create a token.
        usage: skupper token create <file> [options]
        output: |
          Token file <file> created
          The token expires after 1 use or after 15 minutes
        arguments:
          - name: file
            variable: string
            description: |
              The name of the token file.
          - property: validFor
            name: --expiry
            variable: duration
            default: 15m
          - property: claims
            name: --uses
            default: 1
      - title: skupper link
        description: |
          Display help for link commands and exit.
      - resource: Link
        title: skupper link create
        description: |
          Create a link.

          @resource_description@
        usage: skupper link create <file> [options]
        output: |
          Waiting for status...
          Link "<name>" is active
          You can now safely delete <file>
        arguments:
          - name: file
            description: |
              The name of the token file.
          - property: cost
      - title: skupper link delete
        usage: skupper link delete <name>
      - title: skupper link status
        output: |
          NAME    STATUS   COST
          west    Active   1
          south   Error    10

          Links from remote sites:

          None
  - title: Service exposure
    commands:
      - title: skupper connector
        description: |
          Display help for connector commands and exit.
      - resource: Connector
        title: skupper connector create
        description: |
          Create a connector.

          @resource_description@
        usage: skupper connector create <name> [options]
        examples: |
          # Create a connector for a database
          skupper connector create database --workload deployment/postgresql --port 5432
        output: |
          Waiting for status...
          Connector "<name>" is ready
        arguments:
          - name: name
            variable: string
            description: |
              The name of the connector resource.
          - property: routingKey
            default: _value of name_
          - name: --workload
            variable: string
          - property: port
          - property: selector
          - property: host
          - property: enableTLS
          - property: tlsCredentials
          - property: type
          - property: includeNotReady
      - title: skupper connector delete
        description: |
          Delete a connector.
        usage: skupper connector delete <name>
        output: |
          Waiting for deletion to complete...
          Connector "<name>" is deleted
        arguments:
          - name: name
            variable: string
            description: |
              The name of the connector resource.
      - title: skupper connector status
        description: |
          Show the status of connectors in the current site.
        usage: skupper connector status
        output: |
          NAME       ROUTING-KEY   SELECTOR         HOST   PORT   MATCHING-LISTENERS
          backend    backend       app=backend      -      8080   1
          database   database      app=postgresql   -      5342   1
      - title: skupper listener
        description: |
          Display help for listener commands and exit.
      - resource: Listener
        title: skupper listener create
        description: |
          Create a listener.

          @resource_description@
        usage: skupper listener create <name> [options]
        examples: |
          # Create a listener for a database
          skupper listener create database --host database --port 5432
        output: |
          Waiting for status...
          Listener "<name>" is ready
        arguments:
          - name: name
            variable: string
            description: |
              The name of the listener resource.
          - property: routingKey
            default: _value of name_
          - property: host
          - property: port
          - property: enableTLS
          - property: tlsCredentials
          - property: type
      - title: skupper listener delete
        description: |
          Delete a listener.
        usage: skupper listener delete <name>
        output: |
          Waiting for deletion to complete...
          Listener "<name>" is deleted
        arguments:
          - name: name
            variable: string
            description: |
              The name of the listener resource.
      - title: skupper listener status
        description: |
          Show the status of listeners in the current site.
        usage: skupper listener status
        output: |
          NAME       ROUTING-KEY   HOST       PORT   MATCHING-CONNECTORS
          backend    backend       backend    8080   1
          database   database      database   5432   1
  # - title: Platform operations
  #   commands:
  #     - title: skupper platform
  #       description: |
  #         Display help for platform commands and exit.
  #     - title: skupper platform install
  #     - title: skupper platform uninstall
  #     - title: skupper platform switch
  - title: Debug operations
    commands:
      - title: skupper debug
        description: |
          Display help for debug commands and exit.
      - title: skupper debug dump
        description: |
          Generate a debug dump file.
        usage: skupper debug dump [file]
        output: |
          Debug dump file generated at <file>
  - title: Other operations
    commands:
      # - title: skupper network status
      - title: skupper version
