groups:
  - name: Sites and networks
    concepts:
      - name: site
        links:
          - name: Network concept
            url: /concepts/network.html
          - name: Link concept
            url: /concepts/link.html
        description: |
          A place where components of your application are running.
          Sites are linked to form application networks.
        overview: |
          - XXX usually a namespace
          - XXX on different platforms
          - XXX sites can be added and removed dynamically
      - name: network
        links:
          - name: Site concept
            url: /concepts/site.html
          - name: Link concept
            url: /concepts/link.html
        overview: |
          - XXX One network corresponds to one distributed application.
      - name: platform
        description: |
          A system for running workloads.
        overview: |
          - XXX enumerate them
      - name: namespace
        overview: |
          - XXX what do they look like on each platform?
  - name: Site linking
    concepts:
      - name: link
        links:
          - name: Network concept
            url: /concepts/network.html
        description: |
          A site-to-site communication channel. Links serve as a
          transport for application connections and requests.  A set
          of linked sites constitute a network.
        overview: |
          - XXX A vessel for bidirectional application traffic
          - XXX link topology
          - XXX link cost
          - XXX only one direction needed
      - name: link access
      - name: grant
        rename: Access grant
        links:
          - name: Access token concept
            url: /concepts/claim.html
          - name: Token issue command
            url: /commands/token-issue.html
        description: |
          Permission to redeem access tokens for links to the local
          site.  A remote site can use a token containing the grant
          URL and secret code to obtain a certificate signed by the
          grant's certificate authority (CA), within a certain
          expiration window and for a limited number of redemptions.
      - name: claim
        rename: Access token
        links:
          - name: Access grant concept
            url: /concepts/grant.html
          - name: Token redeem command
            url: /commands/token-redeem.html
        description: |
          A transferrable token redeemable for a link to a remote
          site.  An access token contains the URL and secret code of a
          corresponding access grant.
  - name: Service exposure
    concepts:
      - name: service
        overview: |
          - XXX at the network level
          - XXX a listener and a connector bound together by a routing key
      - name: listener
        links:
          - name: Connector concept
            url: /concepts/connector.html
        description: |
          Binds a connection endpoint in the local site to target
          workloads in remote sites.
      - name: connector
        links:
          - name: Listener concept
            url: /concepts/listener.html
        description: |
          Binds target workloads in the local site to listeners in
          remote sites.
        overview: |
          - A connector targets a workload in the local site (or
            reachable on the local network).
          - A connector forwards connections from matching listeners
            at remote sites to the workload in the local site.
      - name: routing key
        links:
          - name: Listener concept
            url: /concepts/listener.html
          - name: Connector concept
            url: /concepts/connector.html
