groups:
  - name: Networks and sites
    concepts:
      - name: network
        description: |
          Theses:

            - One network corresponds to one distributed application.
      - name: site
        resource: Site
        command: site
        description: |
          A site is a place where components of your application are
          running.  Sites are linked to form application networks.
  - name: Site linking
    concepts:
      - name: link
        resource: Link
        command: link
        links:
          - name: Network concept
            url: /concepts/network.html
        description: |
          A link is a site-to-site communication channel. Links serve
          as a transport for application connections and requests.  A
          set of linked sites constitute a network.
      - name: grant
        resource: Grant
        command: token issue
        links:
          - name: Token concept
            url: /concepts/claim.html
        description: |
          Permission to redeem tokens for links to the local site.  A
          remote site can use a token containing the grant URL and
          secret to obtain a certificate signed by the grant's
          certificate authority (CA), within a certain expiration
          period and for a limited number of redemptions.
      - name: claim
        rename: token
        resource: Claim
        command: token redeem
        links:
          - name: Grant concept
            url: /concepts/grant.html
        description: |
          A transferrable authentication token redeemable for a link
          to a remote site.  A token contains the URL and secret of a
          corresponding grant.
  - name: Service exposure
    concepts:
      - name: listener
        resource: Listener
        command: listener
        links:
          - name: Connector concept
            url: /concepts/connector.html
        description: |
          A listener is a local connection endpoint bound to servers
          in remote sites.
      - name: connector
        resource: Connector
        command: connector
        links:
          - name: Listener concept
            url: /concepts/listener.html
        description: |
          A connector binds local servers to listeners in remote
          sites.
      - name: routing key
        links:
          - name: Listener concept
            url: /concepts/listener.html
          - name: Connector concept
            url: /concepts/connector.html
