concepts:
  - name: network
    links:
      - title: Site concept
        url: /concepts/site.html
      - title: Link concept
        url: /concepts/link.html
    description: |
      A _network_ is a set of linked sites. A Skupper network is also
      known as an _application network_ or _virtual application
      network_ (VAN).

      Each network is meant for one distributed application.  This
      provides isolation from other applications and networks.

      <img src="images/network-1.svg"/>
      <img src="images/network-2.svg"/>
      <img src="images/network-3.svg"/>
  - name: site
    links:
      - title: Network concept
        url: /concepts/network.html
      - title: Link concept
        url: /concepts/link.html
      - title: Platform concept
        url: /concepts/platform.html
      - title: Namespace concept
        url: /concepts/namespace.html
    description: |
      A _site_ is a place on the network where workloads are running.
      Sites are linked to form application networks.

      <img src="images/site-1.svg"/>
      <img src="images/site-2.svg"/>
      <img src="images/site-3.svg"/>
    overview: |
      - XXX usually a namespace
      - XXX on different platforms
      - XXX sites can be added and removed dynamically
      - Also called Virtual Application Network (VAN), also application network
      - Sites run on platforms
  - name: platform
    description: |
      A _platform_ is a system for running application workloads.  A
      platform hosts sites.

      <img src="images/platform-1.svg"/>
      <img src="images/platform-2.svg"/>
    overview: |
      - XXX enumerate them
      - Platforms have namespaces (usually)
      - Platforms can host sites
  - name: namespace
    links:
      - title: Platform concept
        url: /concepts/platform.html
      - title: Site concept
        url: /concepts/site.html
    description: |
      A _namespace_ is a named area for a related set of resources.

      <img src="images/namespace-1.svg"/>
      <img src="images/namespace-2.svg"/>
      <img src="images/namespace-3.svg"/>
    overview: |
      - XXX what do they look like on each platform?
      - Each site corresponds to one namespace
      - It's a subdivision of a platform.
  - name: link
    links:
      - title: Network concept
        url: /concepts/network.html
      - title: Link access concept
        url: /concepts/link-access.html
    description: |
      A _link_ is a channel for communication between sites.  Links
      serve as a transport for application connections and requests.
      A set of linked sites constitutes a network.

      <img src="images/link-1.svg"/>
      <img src="images/link-2.svg"/>
      <img src="images/link-3.svg"/>
    overview: |
      - XXX A vessel for bidirectional application traffic
      - XXX link topology
      - XXX link cost
      - XXX only one direction needed
  - name: link access
    description: |
      A _link access_ is an external access point for accepting links.
    overview: |
      - RouterAccess provides link access
  - name: access grant
    links:
      - title: Access token concept
        url: /concepts/access-token.html
      - title: Link concept
        url: /concepts/link.html
      - title: Token issue command
        url: /commands/token-issue.html
    description: |
      An _access grant_ enables redemption of access tokens.  A remote
      site can use a token containing the grant URL and secret code to
      obtain a certificate signed by the grant's certificate authority
      (CA), within a certain expiration window and for a limited
      number of redemptions.
  - name: access token
    links:
      - title: Access grant concept
        url: /concepts/access-grant.html
      - title: Link concept
        url: /concepts/link.html
      - title: Token redeem command
        url: /commands/token-redeem.html
    description: |
      An _access token_ is redeemable for a link to a remote site.  An
      access token contains the URL and secret code of a corresponding
      access grant.

      <img src="images/access-token-1.svg"/>
      <img src="images/access-token-2.svg"/>
    overview: |
      - Generated from an access grant
  - name: service
    links:
      - title: Listener concept
        url: /concepts/listener.html
      - title: Connector concept
        url: /concepts/connector.html
      - title: Routing key concept
        url: /concepts/routing-key.html
    description: |
      A _service_ is an application component exposed on the network.

      <img src="images/service-1.svg"/>
      <img src="images/service-2.svg"/>
    overview: |
      - XXX at the network level
      - XXX a listener and a connector bound together by a routing key
  - name: listener
    links:
      - title: Connector concept
        url: /concepts/connector.html
    description: |
      A _listener_ binds a local connection endpoint to connectors in
      remote sites.
  - name: connector
    links:
      - title: Listener concept
        url: /concepts/listener.html
    description: |
      A _connector_ binds a local workload to listeners in remote
      sites.
    overview: |
      - A connector targets a workload in the local site (or
        reachable on the local network).
      - A connector forwards connections from matching listeners
        at remote sites to the workload in the local site.
  - name: routing key
    description: |
      A _routing key_ is an identifier for matching listeners to
      connectors.
    links:
      - title: Listener concept
        url: /concepts/listener.html
      - title: Connector concept
        url: /concepts/connector.html
groups:
  - name: Networks and sites
    concepts:
      - network
      - site
      - platform
      - namespace
  - name: Site linking
    concepts:
      - link
      - link access
      - access grant
      - access token
  - name: Service exposure
    concepts:
      - service
      - listener
      - connector
      - routing key
