concepts:
  - name: network
    links:
      - title: Site concept
        url: /concepts/site.html
      - title: Link concept
        url: /concepts/link.html
    description: |
      A _network_ is a set of linked sites that host a distributed
      application.  A Skupper network is also known as an _application
      network_ or _virtual application network_ (VAN).

      Each network is meant for one distributed application.  This
      provides a high level of isolation from other applications and
      networks.

      <img src="images/network-1.svg" width="480"/>
      <img src="images/network-2.svg" width="480"/>
      <img src="images/network-3.svg" width="480"/>
  - name: site
    links:
      - title: Network concept
        url: /concepts/network.html
      - title: Link concept
        url: /concepts/link.html
    description: |
      A place where components of your application are running.
      Sites are linked to form application networks.
    overview: |
      - XXX usually a namespace
      - XXX on different platforms
      - XXX sites can be added and removed dynamically
      - Also called Virtual Application Network (VAN), also application network
  - name: platform
    description: |
      A system for running workloads.
    overview: |
      - XXX enumerate them
      - Platforms have namespaces (usually)
      - Platforms can host sites
  - name: namespace
    description: |
      A named area for a related set of resources and components.
    overview: |
      - XXX what do they look like on each platform?
      - Each site corresponds to one namespace
  - name: link
    links:
      - title: Network concept
        url: /concepts/network.html
    description: |
      A site-to-site communication channel. Links serve as a
      transport for application connections and requests.  A set
      of linked sites constitute a network.
    overview: |
      - XXX A vessel for bidirectional application traffic
      - XXX link topology
      - XXX link cost
      - XXX only one direction needed
  - name: link access
    description: |
      An external access point for receiving links
    overview: |
      - RouterAccess provides link access
  - name: access grant
    links:
      - title: Access token concept
        url: /concepts/claim.html
      - title: Token issue command
        url: /commands/token-issue.html
    description: |
      Permission to redeem access tokens for links to the local
      site.  A remote site can use a token containing the grant
      URL and secret code to obtain a certificate signed by the
      grant's certificate authority (CA), within a certain
      expiration window and for a limited number of redemptions.
  - name: access token
    links:
      - title: Access grant concept
        url: /concepts/grant.html
      - title: Token redeem command
        url: /commands/token-redeem.html
    description: |
      A transferrable token redeemable for a link to a remote
      site.  An access token contains the URL and secret code of a
      corresponding access grant.
  - name: service
    description: |
      An application component exposed on the network
    overview: |
      - XXX at the network level
      - XXX a listener and a connector bound together by a routing key
  - name: listener
    links:
      - title: Connector concept
        url: /concepts/connector.html
    description: |
      A binding from a local connection endpoint to connectors in
      remote sites.
  - name: connector
    links:
      - title: Listener concept
        url: /concepts/listener.html
    description: |
      A binding from a local workload to listeners in remote sites.
    overview: |
      - A connector targets a workload in the local site (or
        reachable on the local network).
      - A connector forwards connections from matching listeners
        at remote sites to the workload in the local site.
  - name: routing key
    description: |
      An identifier for matching listeners to connectors
    links:
      - title: Listener concept
        url: /concepts/listener.html
      - title: Connector concept
        url: /concepts/connector.html
groups:
  - name: Networks and sites
    concepts:
      - network
      - site
      - platform
      - namespace
  - name: Site linking
    concepts:
      - link
      - link access
      - access grant
      - access token
  - name: Service exposure
    concepts:
      - service
      - listener
      - connector
      - routing key
