groups:
  - title: Site configuration
    resources:
      - name: Site
        description: |
          A [site][site] is a place where components of your application are
          running.  Sites are linked to form application
          [networks][network].

          There can be only one site definition per namespace.

          [site]: concepts.html#site
          [network]: concepts.html#network
        examples:
          - description: A minimal site definition
            yaml: |
              apiVersion: skupper.io/v1alpha1
              kind: Site
              metadata:
                name: east
                namespace: hello-world-east
        properties:
          - name: enableLinkAccess
            type: boolean
            description: |
              Enable external access for links from remote sites.
          - name: linkAccessType
            type: string
            description: |
              Select the means of opening external access.
            default: |
              `route` if the environment is OpenShift, otherwise
              `loadbalancer`
            choices: [route, loadbalancer, nodeport, ingress]
          - name: linkAccessHost
            type: string
            description: |
              The host or IP address at which to expose link access.
          - name: serviceAccount
          - name: settings
  - title: Site linking
    resources:
      - name: Grant
        description: |
          An offer to accept links to the local site.  A remote site
          can use a claim containing the grant URL and secret to
          obtain a certificate signed by the grant's certificate
          authority (CA), within a certain expiration period and for a
          limited number of claims.
        properties:
          - name: claims
            notes: Consider maxClaims, claimsAllowed, and maxClaimsAllowed
          - name: validFor
            notes: |
              Look for what would be conventional for this.
              "validFor" doesn't necessarily make it clear that it's
              about time: "valid for 3 uses".
          - name: secret
      - name: Claim
        description: |
          A verifiable assertion of permission to link to a remote
          site.  A claim contains the URL and secret of a previous
          grant.
        properties:
          - name: url
          - name: secret
          - name: ca
  - title: Service exposure
    resources:
      - name: Connector
        description: |
          A [connector][connector] binds local servers to listeners in
          remote sites.

          Each site can have multiple connector definitions.

          [connector]: concepts.html#connector
        examples:
          - description: |
              A connector in site East for the Hello World backend service
            yaml: |
              apiVersion: skupper.io/v1alpha1
              kind: Connector
              metadata:
                name: backend
                namespace: hello-world-east
              spec:
                routingKey: backend
                port: 8080
                selector: app=backend
        properties:
          - name: routingKey
            description: |
              The identifier used to route traffic from listeners to
              connectors.  To connect to a service at a remote site, the
              listener and connector must have matching routing keys.
          - name: selector
            description: |
              A Kubernetes [label selector][selector] for targeting server
              pods.

              [selector]: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors
          - name: host
            description: |
              The hostname or IP address of the server.  This is an
              alternative to `selector` for specifying the target
              server.
          - name: port
            description: |
              The port number of the server listener.
          - name: enableTLS
            type: boolean
            description: |
              Use TLS to encrypt communication between the router and servers.

              By default, the TLS credentials are generated and stored in
              a secret at XXX.
          - name: tlsCredentials
            description: |
              The name of a Kubernetes secret containing the trusted
              server certificate (typically a CA).

              It can optionally include a client certificate and key for
              mutual TLS.
          - name: type
            notes: |
              What is this again?  I think we need a qualifier on "type".
          - name: includeNotReady
      - name: Listener
        description: |
          A [listener][listener] is a local connection endpoint bound to
          servers in remote sites.

          Each site can have multiple listener definitions.

          [listener]: concepts.html#listener
        examples:
          - description: |
              A listener in site West for the Hello World backend service
              in site East
            yaml: |
              apiVersion: skupper.io/v1alpha1
              kind: Listener
              metadata:
                name: backend
                namespace: hello-world-west
              spec:
                routingKey: backend
                port: 8080
                host: backend
        properties:
          - name: routingKey
            description: |
              The identifier used to route traffic from listeners to
              connectors.  To connect to a service at a remote site, the
              listener and connector must have matching routing keys.
          - name: host
            description: |
              The hostname or IP address of the local listener.  Clients
              at this site use the listener host and port to
              establish connections to the remote service.
          - name: port
            description: |
              The port of the local listener.  Clients at this site use
              the listener host and port to establish connections to
              the remote service.
          - name: enableTLS
            type: boolean
            description: |
              Use TLS to encrypt communication between clients and the router.

              By default, the TLS credentials are generated and stored in
              a secret at XXX.
          - name: tlsCredentials
            description: |
              The name of a Kubernetes secret containing TLS
              credentials.  The secret contains the trusted server
              certificate (typically a CA).

              It can optionally include a client certificate and key for
              mutual TLS.
          - name: tlsCA
            type: string
            notes: |
              Doesn't this follow, if the TLS credentials can be generated?
          - name: type
            notes: |
              What is this again?  I think we need a qualifier on "type".
  - title: Advanced stuff
    resources:
      - name: Link
        description: |
          A [link][link] is a site-to-site communication channel. Links
          serve as a transport for application connections and requests.

          [link]: concepts.html#link
        examples:
          - description: A typical link definition
            yaml: |
              apiVersion: skupper.io/v1alpha1
              kind: Link
              metadata:
                name: link-to-west
                namespace: hello-world-east
              spec:
                [...]
        properties:
          - name: tlsCredentials
            description: |
              The name of a Kubernetes secret containing TLS
              credentials. The secret contains the trusted server
              certificate (typically a CA).

              It can optionally include a client certificate and key for
              mutual TLS.
          - name: cost
          - name: interRouter
          - name: edge
          - name: noClientAuth
      - name: LinkAccess
        description: |
          A point of external access for links from remote sites.  A
          LinkAccess configures the router to accept inter-router
          links and creates the Kubernetes resources for external
          access.
        examples:
          - description: A typical link access definition
            yaml: |
              apiVersion: skupper.io/v1alpha1
              kind: LinkAccess
              metadata:
                name: skupper-router
              spec:
                roles:
                - role: inter-router
                  port: 55671
                - role: edge
                  port: 45671
                tlsCredentials: skupper-site-server
        properties:
          - name: roles
          - name: tlsCredentials
            description: |
              The name of a Kubernetes secret containing the trusted
              server certificate (typically a CA).

              It can optionally include a client certificate and key for
              mutual TLS.
          - name: ca
            description: |
              The name of a Kubernetes secret containing a CA for
              generating TLS credentials.  If the `tlsCredentials`
              property is not set, the controller uses `ca` to
              generate them.
            notes: |
              Consider tlsCA.  And "ca" often means "this is what I trust".  This thing has a different meaning.
          - name: bindHost
            notes: |
              Just host?  What does "bind" do here to clarify?  I have a related attribute on site: linkAccessHost.
          - name: subjectAlternativeNames
          - name: options
  - title: Internal stuff
    resources:
      - name: SecuredAccess
        description: |
          A generic resource for exposing a workload by creating the
          necessary service and ingress resources and optionally
          generating TLS credentials.
        properties:
          - name: ports
          - name: selector
          - name: ca
          - name: certificate
          - name: accessType
          - name: options
      - name: Certificate
        properties:
          - name: ca
          - name: subject
          - name: hosts
          - name: client
          - name: server
          - name: signing
