name: AttachedConnectorBinding
platforms: [Kubernetes]
related_resources: [attached-connector]
links: [skupper/attached-connectors]
description: |
  A binding to an attached connector in a peer namespace.
metadata:
  include_properties: [metadata/*]
  properties:
    - name: name
      description: |
        @description@

        The name must be the same as that of the associated
        AttachedConnector resource in the connector namespace.
spec:
  include_properties: [connector/spec/routingKey, connector/spec/exposePodsByName, settings]
  properties:
    - name: connectorNamespace
      description: |
        The name of the namespace where the associated
        AttachedConnector is located.
status:
  include_properties: [status/*, connector/status/hasMatchingListener]
  exclude_properties: [status/message]
