name: Connector
related_resources: [Listener]
links: [skupper/service_exposure]
description: |
  A binding from a local workload to listeners in remotes sites.

  Each site can have multiple connector resources.
examples:
  - description: |
      A connector in site East for the Hello World backend service
    yaml: |
      apiVersion: skupper.io/v2alpha1
      kind: Connector
      metadata:
        name: backend
        namespace: hello-world-east
      spec:
        routingKey: backend
        port: 8080
        selector: app=backend
metadata:
  include_properties: [metadata/*]
spec:
  include_properties: [connector/spec/*, settings]
status:
  include_properties: [status/*, connector/status/*]
