- title: Primary resources
  objects:
    - site
    - link
    - listener
    - connector
- title: Sites and site linking
  objects:
    - site
    - link
    - access-grant
    - access-token
    - router-access
- title: Service exposure
  objects:
    - listener
    - connector
    - attached-connector
    - attached-connector-binding
