groups:
  - title: Primary resources
    resources:
      - Site
      - Link
      - Listener
      - Connector
  - title: Site linking
    resources:
      - Link
      - AccessGrant
      - AccessToken
      - RouterAccess
  - title: Service exposure
    resources:
      - Listener
      - Connector
      - AttachedConnector
      - AttachedConnectorAnchor
