groups:
  - title: Primary resources
    resources:
      - Site
      - Link
      - Listener
      - Connector
  - title: Sites and site linking
    resources:
      - Site
      - Link
      - AccessGrant
      - AccessToken
      - RouterAccess
  - title: Service exposure
    resources:
      - Listener
      - Connector
      - AttachedConnector
      - AttachedConnectorBinding
