groups:
  - name: Sites
    resources:
      - Site
  - name: Site linking
    resources:
      - AccessGrant
      - AccessToken
      - Link
  - name: Service exposure
    resources:
      - Listener
      - Connector
      - AttachedConnector
      - AttachedConnectorAnchor
