name: Link
related_resources: [AccessToken]
links: [skupper/site_linking]
description: |
  A channel for communication between sites.  Links carry application
  connections and requests.  A set of linked sites constitutes a
  network.

  **Note:** Links are not usually created directly.  Instead, you can
  use an [access token][token] to obtain a link.

  [token]: access-token.html
metadata:
  include_properties: [metadata/*]
spec:
  include_properties: [endpoints, settings]
  properties:
    - name: cost
      default: 1
      links: [skupper/load_balancing]
      description: |
        The configured routing cost of sending traffic over
        the link.
    - name: endpoints
      group: null
    - name: tlsCredentials
      links: [skupper/router_tls, kubernetes/tls_secrets, skupper/system_tls_credentials]
      description: |
        The name of a bundle of certificates used for mutual TLS
        router-to-router communication.  The bundle contains the
        client certificate and key and the trusted server certificate
        (usually a CA).

        On Kubernetes, the value is the name of a Secret in the
        current namespace.  On Docker, Podman, and Linux, the value is
        the name of a directory under `input/certs/` in the current
        namespace.
status:
  include_properties: [status/*]
  properties:
    - name: status
    - name: message
    - name: remoteSiteId
      description: |
        The unique ID of the site linked to.
    - name: remoteSiteName
      description: |
        The name of the site linked to.
    - name: conditions
      description: |
        @description@

        - `Configured` - The link configuration has been applied to
          the router.
        - `Operational` - The link to the remote site is active.
        - `Ready` - The link is ready to use.  All other conditions
          are true.
