apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: links.skupper.io
spec:
  group: skupper.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                interRouter:
                  type: object
                  properties:
                    host:
                      type: string
                    port:
                      type: integer
                  required:
                    - host
                    - port
                edge:
                  type: object
                  properties:
                    host:
                      type: string
                    port:
                      type: integer
                  required:
                    - host
                    - port
                tlsCredentials:
                  type: string
                cost:
                  type: integer
                noClientAuth:
                  type: boolean
              required:
                - interRouter
                - edge
            status:
              type: object
              properties:
                configured:
                  type: boolean
                url:
                  type: string
                active:
                  type: boolean
                site:
                  type: string
                status:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Url
        type: string
        description: The host and port the router has been configured to link to
        jsonPath: .status.url
      - name: Configured
        type: boolean
        description: Whether the router has been configured to try and establish the link
        jsonPath: .status.configured
      - name: Active
        type: boolean
        description: Whether link is active
        jsonPath: .status.active
      - name: Site Name
        type: string
        description: The name of the site linked to
        jsonPath: .status.site
      - name: Status
        type: string
        description: The status of the link
        jsonPath: .status.status
  scope: Namespaced
  names:
    plural: links
    singular: link
    kind: Link
