apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: connectors.skupper.io
spec:
  group: skupper.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                routingKey:
                  type: string
                port:
                  type: integer
                selector:
                  type: string
                host:
                  type: string
                tlsCredentials:
                  type: string
                type:
                  type: string
                includeNotReady:
                  type: boolean
              required:
              - routingKey
              - port
              oneOf:
                - properties:
                  required:
                  - selector
                - properties:
                  required:
                  - host
            status:
              type: object
              properties:
                active:
                  type: boolean
                status:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Routing Key
        type: string
        description: The key that ties connectors and listeners together
        jsonPath: .spec.routingKey
      - name: Port
        type: integer
        description: The port to connect to
        jsonPath: .spec.port
      - name: Host
        type: string
        description: The host to connect to
        jsonPath: .spec.host
      - name: Selector
        type: string
        description: The selector that identifies the pods to connect to
        jsonPath: .spec.selector
      - name: Active
        type: boolean
        description: Whether connector is active
        jsonPath: .status.active
      - name: Status
        type: string
        description: The status of the connector
        jsonPath: .status.status
  scope: Namespaced
  names:
    plural: connectors
    singular: connector
    kind: Connector
