apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: listeners.skupper.io
spec:
  group: skupper.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                routingKey:
                  type: string
                host:
                  type: string
                port:
                  type: integer
                tlsCredentials:
                  type: string
                type:
                  type: string
              required:
                - routingKey
                - host
                - port
            status:
              type: object
              properties:
                active:
                  type: boolean
                status:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Routing Key
        type: string
        description: The key that ties connectors and listeners together
        jsonPath: .spec.routingKey
      - name: Port
        type: integer
        description: The port the service listens on
        jsonPath: .spec.port
      - name: Host
        type: string
        description: The name of the service
        jsonPath: .spec.host
      - name: Active
        type: boolean
        description: Whether listener is active
        jsonPath: .status.active
      - name: Status
        type: string
        description: The status of the listener
        jsonPath: .status.status
  scope: Namespaced
  names:
    plural: listeners
    singular: listener
    kind: Listener
