apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: links.skupper.io
spec:
  group: skupper.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                endpoints:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      host:
                        type: string
                      port:
                        type: string
                      group:
                        type: string
                tlsCredentials:
                  type: string
                cost:
                  type: integer
                noClientAuth:
                  type: boolean
              required:
                - endpoints
            status:
              type: object
              properties:
                configured:
                  type: boolean
                active:
                  type: boolean
                status:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Configured
        type: boolean
        description: Whether the router has been configured to try and establish the link
        jsonPath: .status.configured
      - name: Active
        type: boolean
        description: Whether link is active
        jsonPath: .status.active
      - name: Status
        type: string
        description: The status of the link
        jsonPath: .status.status
  scope: Namespaced
  names:
    plural: links
    singular: link
    kind: Link
