groups:
  - title: Site operations
    commands:
      - site
  - title: Site linking
    commands:
      - token
      - link
  - title: Service exposure
    commands:
      - listener
      - connector
  - title: System operations
    commands:
      - system
  - title: Debugging operations
    commands:
      - debug
  - title: Other operations
    commands:
      - version
