name: system
platforms: [Docker, Podman, Linux]
related_concepts: [platform]
subcommands:
  - name: install
    related_commands: [system/uninstall]
    description: |
      Install the Skupper components.

      This creates the router configuration, TLS certificates, and
      systemd unit file for the current namespace.  On Docker or
      Podman, it also creates containers for Skupper components.
    include_options: [context/namespace, global/*]
  - name: uninstall
    related_commands: [system/install]
    description: |
      Remove the Skupper components.

      This removes the router configuration, TLS certificates, and
      systemd unit file for the current namespace.  On Docker or
      Podman, it also removes the containers for Skupper components.
    include_options: [context/namespace, global/*]
  - name: start
    related_commands: [system/stop]
    description: |
      Start up the Skupper components for the current site.

      This starts the systemd service for the current namespace.

      <!-- Maybe: If not installed yet, run install -->
    include_options: [context/namespace, global/*]
  - name: stop
    related_commands: [system/start]
    description: |
      Shut down the Skupper components for the current site.

      This stops the systemd service for the current namespace.
    include_options: [context/namespace, global/*]
  - name: reload
    description: |
      Reload the site configuration.

      This restarts the systemd service for the current namespace.
  # - name: apply
  #   description: |
  #     Apply resource configuration from files or standard input.

  #     <!-- File locations and names -->
  #   include_options: [context/namespace, global/*]
  - name: status
    description: |
      Display the status of the system.
    include_options: [context/namespace, global/*]
