name: connector
related_concepts: [listener, routing key]
links: [skupper/service_exposure]
description: |
  A **connector** binds a local workload to
  **[listeners](listener.html)** in remote **[sites](site.html)**.
  Listeners and connectors are matched using **[routing
  keys](routing-key.html)**.

  <figure>
    <img src="images/connector-model.svg"/>
    <figcaption>The connector model</figcaption>
  </figure>

  A site has zero or more connectors.  Each connector has an
  associated workload and routing key.  The workload can be specified
  as a Kubernetes pod selector or as the host and port of a local
  network service.

  <figure>
    <img src="images/routing-key-model.svg"/>
    <figcaption>Listeners and connectors associated by routing key</figcaption>
  </figure>

  The routing key is a string identifier that binds the connector to
  listeners in remote sites.  Skupper routers forward client
  connections across the network from listeners to connectors with
  matching routing keys.  The connectors then forward the client
  connections to the workload servers.

  <figure>
    <img src="images/connector-1.svg"/>
    <figcaption>A connector bound to a set of servers</figcaption>
  </figure>
