groups:
  - title: Sites
    concepts:
      - site
      - workload
      - platform
  - title: Site linking
    concepts:
      - link
      - network
      - access token
  - title: Service exposure
    concepts:
      - listener
      - connector
      - routing key
