groups:
  - title: Sites
    concepts:
      - site
      - workload
      - platform
  - title: Networks
    concepts:
      - network
      - link
      - access token
  - title: Service exposure
    concepts:
      - listener
      - connector
      - routing key
