groups:
  - title: Sites
    concepts:
      - site
      - workload
      - platform
  - title: Networks
    concepts:
      - network
      - link
      - access token
  - title: Services
    concepts:
      - listener
      - connector
      - routing key
  - title: Applications
    concepts:
      - application
      - component
