name: link
related_concepts: [network, site, access token]
description: |
  A _link_ is a channel for communication between sites.  Links
  serve as a transport for application connections and requests.
  A set of linked sites constitutes a network.

  To create a link to a remote site, the remote site must provide
  _link access_.  A link access is an external access point for
  accepting links.

  Application connections and requests flow across links in both
  directions.  A linked site can communicate with any other site
  in the network of sites, even if it is not linked directly.

  Links are encrypted and authenticated using mutual TLS.  You can
  use access tokens to create links.

  <figure>
    <img src="images/link-1.svg"/>
    <figcaption>A link joining two sites to create a simple network</figcaption>
  </figure>

  <figure>
    <img src="images/link-2.svg"/>
    <figcaption>A site with two links, to two remote sites</figcaption>
  </figure>

  <figure>
    <img src="images/link-3.svg"/>
    <figcaption>A larger network with links to a central hub site</figcaption>
  </figure>
