name: listener
related_concepts: [connector, routing key]
description: |
  A _listener_ binds a local connection endpoint to connectors in
  remote sites.

  <figure>
    <img src="images/listener-1.svg"/>
    <figcaption>A listener with multiple clients connecting
    through it</figcaption>
  </figure>
overview: |
  - Local workloads can connect to the listener
