name: listener
related_concepts: [connector, routing key]
description: |
  A **listener** binds a local connection endpoint to
  **[connectors](connector.html)** in remote **[sites](site.html)**.
  Listeners and connectors are bound using **[routing
  keys](routing-key.html)**.

  <figure>
    <img src="images/listener-model.svg"/>
    <figcaption>The listener model</figcaption>
  </figure>

  A site has zero or more listeners.  Each listener has an associated
  connection endpoint (host:port) and routing key.

  <figure>
    <img src="images/routing-key-model.svg"/>
    <figcaption>Listeners and connectors associated by routing key</figcaption>
  </figure>

  The routing key is a string identifier that binds the listener to
  connectors in remote sites.  Skupper routers forward client
  connections to listeners across the network to connectors with
  matching routing keys.  The connectors then forward the client
  connections to the workload servers.

  <figure>
    <img src="images/listener-1.svg"/>
    <figcaption>A listener with multiple clients connecting
    through it</figcaption>
  </figure>
overview: |
  - Local workloads can connect to the listener
