name: network
related_concepts: [site, link]
description: |
  A _network_ is a set of linked sites. A Skupper network is also
  known as an _application network_ or _virtual application
  network_ (VAN).

  Each network is meant for one distributed application.  This
  provides isolation from other applications and networks.

  <figure>
    <img src="images/network-1.svg"/>
    <figcaption>A simple two-site network</figcaption>
  </figure>

  <figure>
    <img src="images/network-2.svg"/>
    <figcaption>A larger network</figcaption>
  </figure>
