name: platform
related_concepts: [site]
description: |
  A **platform** is a system for running application workloads.  A
  platform hosts sites.  Skupper supports Kubernetes, Docker, Podman,
  and Linux.  Each site in a network can run on any supported
  platform.

  Platforms provide **namespaces** for related workloads and
  resources.  Skupper uses namespaces to host multiple independent
  sites on one instance of a platform, and each site can belong to a
  distinct application network.

  <figure>
    <img src="images/platform-model.svg"/>
    <figcaption>The platform model</figcaption>
  </figure>

  A platform has zero or more namespaces.  Each namespace is
  associated with zero or more workloads.  A namespace is associated
  with zero sites or one site.

  <figure>
    <img src="images/platform-1.svg"/>
    <figcaption>A simple network with sites on two different
    platforms</figcaption>
  </figure>

  <figure>
    <img src="images/platform-2.svg"/>
    <figcaption>Two distinct networks spanning two
    platforms</figcaption>
  </figure>
